#pragma once

// (C) Copyright Takayama Fumihiko 2018.
// Distributed under the Boost Software License, Version 1.0.
// (See http://www.boost.org/LICENSE_1_0.txt)

#include <IOKit/hid/IOHIDUsageTables.h>
#include <functional>
#include <iostream>
#include <type_safe/strong_typedef.hpp>

namespace pqrs {
namespace osx {
struct iokit_hid_usage : type_safe::strong_typedef<iokit_hid_usage, int32_t>,
                         type_safe::strong_typedef_op::equality_comparison<iokit_hid_usage>,
                         type_safe::strong_typedef_op::relational_comparison<iokit_hid_usage> {
  using strong_typedef::strong_typedef;
};

inline std::ostream& operator<<(std::ostream& stream, const iokit_hid_usage& value) {
  return stream << type_safe::get(value);
}

//
// iokit_hid_usage_page_generic_desktop
//

constexpr iokit_hid_usage iokit_hid_usage_generic_desktop_pointer(kHIDUsage_GD_Pointer);
constexpr iokit_hid_usage iokit_hid_usage_generic_desktop_mouse(kHIDUsage_GD_Mouse);
constexpr iokit_hid_usage iokit_hid_usage_generic_desktop_keyboard(kHIDUsage_GD_Keyboard);
constexpr iokit_hid_usage iokit_hid_usage_generic_desktop_keypad(kHIDUsage_GD_Keypad);
constexpr iokit_hid_usage iokit_hid_usage_generic_desktop_x(kHIDUsage_GD_X);
constexpr iokit_hid_usage iokit_hid_usage_generic_desktop_y(kHIDUsage_GD_Y);
constexpr iokit_hid_usage iokit_hid_usage_generic_desktop_z(kHIDUsage_GD_Z);
constexpr iokit_hid_usage iokit_hid_usage_generic_desktop_wheel(kHIDUsage_GD_Wheel);

//
// iokit_hid_usage_page_keyboard_or_keypad
//

constexpr iokit_hid_usage iokit_hid_usage_keyboard_error_rollover(kHIDUsage_KeyboardErrorRollOver);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_post_fail(kHIDUsage_KeyboardPOSTFail);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_error_undefined(kHIDUsage_KeyboardErrorUndefined);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_a(kHIDUsage_KeyboardA);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_b(kHIDUsage_KeyboardB);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_c(kHIDUsage_KeyboardC);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_d(kHIDUsage_KeyboardD);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_e(kHIDUsage_KeyboardE);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f(kHIDUsage_KeyboardF);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_g(kHIDUsage_KeyboardG);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_h(kHIDUsage_KeyboardH);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_i(kHIDUsage_KeyboardI);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_j(kHIDUsage_KeyboardJ);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_k(kHIDUsage_KeyboardK);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_l(kHIDUsage_KeyboardL);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_m(kHIDUsage_KeyboardM);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_n(kHIDUsage_KeyboardN);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_o(kHIDUsage_KeyboardO);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_p(kHIDUsage_KeyboardP);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_q(kHIDUsage_KeyboardQ);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_r(kHIDUsage_KeyboardR);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_s(kHIDUsage_KeyboardS);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_t(kHIDUsage_KeyboardT);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_u(kHIDUsage_KeyboardU);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_v(kHIDUsage_KeyboardV);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_w(kHIDUsage_KeyboardW);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_x(kHIDUsage_KeyboardX);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_y(kHIDUsage_KeyboardY);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_z(kHIDUsage_KeyboardZ);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_1(kHIDUsage_Keyboard1);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_2(kHIDUsage_Keyboard2);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_3(kHIDUsage_Keyboard3);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_4(kHIDUsage_Keyboard4);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_5(kHIDUsage_Keyboard5);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_6(kHIDUsage_Keyboard6);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_7(kHIDUsage_Keyboard7);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_8(kHIDUsage_Keyboard8);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_9(kHIDUsage_Keyboard9);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_0(kHIDUsage_Keyboard0);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_return_or_enter(kHIDUsage_KeyboardReturnOrEnter);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_escape(kHIDUsage_KeyboardEscape);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_delete_or_backspace(kHIDUsage_KeyboardDeleteOrBackspace);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_tab(kHIDUsage_KeyboardTab);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_spacebar(kHIDUsage_KeyboardSpacebar);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_hyphen(kHIDUsage_KeyboardHyphen);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_equal_sign(kHIDUsage_KeyboardEqualSign);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_open_bracket(kHIDUsage_KeyboardOpenBracket);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_close_bracket(kHIDUsage_KeyboardCloseBracket);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_backslash(kHIDUsage_KeyboardBackslash);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_non_us_pound(kHIDUsage_KeyboardNonUSPound);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_semicolon(kHIDUsage_KeyboardSemicolon);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_quote(kHIDUsage_KeyboardQuote);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_grave_accent_and_tilde(kHIDUsage_KeyboardGraveAccentAndTilde);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_comma(kHIDUsage_KeyboardComma);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_period(kHIDUsage_KeyboardPeriod);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_slash(kHIDUsage_KeyboardSlash);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_capsLock(kHIDUsage_KeyboardCapsLock);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f1(kHIDUsage_KeyboardF1);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f2(kHIDUsage_KeyboardF2);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f3(kHIDUsage_KeyboardF3);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f4(kHIDUsage_KeyboardF4);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f5(kHIDUsage_KeyboardF5);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f6(kHIDUsage_KeyboardF6);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f7(kHIDUsage_KeyboardF7);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f8(kHIDUsage_KeyboardF8);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f9(kHIDUsage_KeyboardF9);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f10(kHIDUsage_KeyboardF10);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f11(kHIDUsage_KeyboardF11);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f12(kHIDUsage_KeyboardF12);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_print_screen(kHIDUsage_KeyboardPrintScreen);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_scroll_lock(kHIDUsage_KeyboardScrollLock);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_pause(kHIDUsage_KeyboardPause);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_insert(kHIDUsage_KeyboardInsert);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_home(kHIDUsage_KeyboardHome);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_page_up(kHIDUsage_KeyboardPageUp);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_delete_forward(kHIDUsage_KeyboardDeleteForward);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_end(kHIDUsage_KeyboardEnd);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_page_down(kHIDUsage_KeyboardPageDown);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_right_arrow(kHIDUsage_KeyboardRightArrow);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_left_arrow(kHIDUsage_KeyboardLeftArrow);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_down_arrow(kHIDUsage_KeyboardDownArrow);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_up_arrow(kHIDUsage_KeyboardUpArrow);
constexpr iokit_hid_usage iokit_hid_usage_keypad_num_lock(kHIDUsage_KeypadNumLock);
constexpr iokit_hid_usage iokit_hid_usage_keypad_slash(kHIDUsage_KeypadSlash);
constexpr iokit_hid_usage iokit_hid_usage_keypad_asterisk(kHIDUsage_KeypadAsterisk);
constexpr iokit_hid_usage iokit_hid_usage_keypad_hyphen(kHIDUsage_KeypadHyphen);
constexpr iokit_hid_usage iokit_hid_usage_keypad_plus(kHIDUsage_KeypadPlus);
constexpr iokit_hid_usage iokit_hid_usage_keypad_enter(kHIDUsage_KeypadEnter);
constexpr iokit_hid_usage iokit_hid_usage_keypad_1(kHIDUsage_Keypad1);
constexpr iokit_hid_usage iokit_hid_usage_keypad_2(kHIDUsage_Keypad2);
constexpr iokit_hid_usage iokit_hid_usage_keypad_3(kHIDUsage_Keypad3);
constexpr iokit_hid_usage iokit_hid_usage_keypad_4(kHIDUsage_Keypad4);
constexpr iokit_hid_usage iokit_hid_usage_keypad_5(kHIDUsage_Keypad5);
constexpr iokit_hid_usage iokit_hid_usage_keypad_6(kHIDUsage_Keypad6);
constexpr iokit_hid_usage iokit_hid_usage_keypad_7(kHIDUsage_Keypad7);
constexpr iokit_hid_usage iokit_hid_usage_keypad_8(kHIDUsage_Keypad8);
constexpr iokit_hid_usage iokit_hid_usage_keypad_9(kHIDUsage_Keypad9);
constexpr iokit_hid_usage iokit_hid_usage_keypad_0(kHIDUsage_Keypad0);
constexpr iokit_hid_usage iokit_hid_usage_keypad_period(kHIDUsage_KeypadPeriod);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_non_us_backslash(kHIDUsage_KeyboardNonUSBackslash);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_application(kHIDUsage_KeyboardApplication);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_power(kHIDUsage_KeyboardPower);
constexpr iokit_hid_usage iokit_hid_usage_keypad_equal_sign(kHIDUsage_KeypadEqualSign);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f13(kHIDUsage_KeyboardF13);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f14(kHIDUsage_KeyboardF14);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f15(kHIDUsage_KeyboardF15);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f16(kHIDUsage_KeyboardF16);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f17(kHIDUsage_KeyboardF17);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f18(kHIDUsage_KeyboardF18);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f19(kHIDUsage_KeyboardF19);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f20(kHIDUsage_KeyboardF20);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f21(kHIDUsage_KeyboardF21);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f22(kHIDUsage_KeyboardF22);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f23(kHIDUsage_KeyboardF23);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_f24(kHIDUsage_KeyboardF24);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_execute(kHIDUsage_KeyboardExecute);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_help(kHIDUsage_KeyboardHelp);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_menu(kHIDUsage_KeyboardMenu);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_select(kHIDUsage_KeyboardSelect);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_stop(kHIDUsage_KeyboardStop);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_again(kHIDUsage_KeyboardAgain);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_undo(kHIDUsage_KeyboardUndo);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_cut(kHIDUsage_KeyboardCut);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_copy(kHIDUsage_KeyboardCopy);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_paste(kHIDUsage_KeyboardPaste);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_find(kHIDUsage_KeyboardFind);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_mute(kHIDUsage_KeyboardMute);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_volume_up(kHIDUsage_KeyboardVolumeUp);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_volume_down(kHIDUsage_KeyboardVolumeDown);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_locking_caps_lock(kHIDUsage_KeyboardLockingCapsLock);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_locking_num_lock(kHIDUsage_KeyboardLockingNumLock);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_locking_scroll_lock(kHIDUsage_KeyboardLockingScrollLock);
constexpr iokit_hid_usage iokit_hid_usage_keypad_comma(kHIDUsage_KeypadComma);
constexpr iokit_hid_usage iokit_hid_usage_keypad_equal_sign_as400(kHIDUsage_KeypadEqualSignAS400);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_international1(kHIDUsage_KeyboardInternational1);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_international2(kHIDUsage_KeyboardInternational2);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_international3(kHIDUsage_KeyboardInternational3);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_international4(kHIDUsage_KeyboardInternational4);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_international5(kHIDUsage_KeyboardInternational5);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_international6(kHIDUsage_KeyboardInternational6);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_international7(kHIDUsage_KeyboardInternational7);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_international8(kHIDUsage_KeyboardInternational8);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_international9(kHIDUsage_KeyboardInternational9);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_lang1(kHIDUsage_KeyboardLANG1);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_lang2(kHIDUsage_KeyboardLANG2);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_lang3(kHIDUsage_KeyboardLANG3);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_lang4(kHIDUsage_KeyboardLANG4);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_lang5(kHIDUsage_KeyboardLANG5);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_lang6(kHIDUsage_KeyboardLANG6);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_lang7(kHIDUsage_KeyboardLANG7);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_lang8(kHIDUsage_KeyboardLANG8);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_lang9(kHIDUsage_KeyboardLANG9);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_alternate_erase(kHIDUsage_KeyboardAlternateErase);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_sys_req_or_attention(kHIDUsage_KeyboardSysReqOrAttention);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_cancel(kHIDUsage_KeyboardCancel);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_clear(kHIDUsage_KeyboardClear);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_prior(kHIDUsage_KeyboardPrior);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_return(kHIDUsage_KeyboardReturn);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_separator(kHIDUsage_KeyboardSeparator);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_out(kHIDUsage_KeyboardOut);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_oper(kHIDUsage_KeyboardOper);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_clear_or_again(kHIDUsage_KeyboardClearOrAgain);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_cr_sel_or_props(kHIDUsage_KeyboardCrSelOrProps);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_ex_sel(kHIDUsage_KeyboardExSel);
/* 0xA5-0xDF Reserved */
constexpr iokit_hid_usage iokit_hid_usage_keyboard_left_control(kHIDUsage_KeyboardLeftControl);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_left_shift(kHIDUsage_KeyboardLeftShift);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_left_alt(kHIDUsage_KeyboardLeftAlt);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_left_gui(kHIDUsage_KeyboardLeftGUI);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_right_control(kHIDUsage_KeyboardRightControl);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_right_shift(kHIDUsage_KeyboardRightShift);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_right_alt(kHIDUsage_KeyboardRightAlt);
constexpr iokit_hid_usage iokit_hid_usage_keyboard_right_gui(kHIDUsage_KeyboardRightGUI);
/* 0xE8-0xFFFF Reserved */
constexpr iokit_hid_usage iokit_hid_usage_keyboard_reserved(kHIDUsage_Keyboard_Reserved);

//
// iokit_hid_usage_page_leds
//

constexpr iokit_hid_usage iokit_hid_usage_led_caps_lock(kHIDUsage_LED_CapsLock);

//
// iokit_hid_usage_page_button
//

constexpr iokit_hid_usage iokit_hid_usage_button_1(kHIDUsage_Button_1);
constexpr iokit_hid_usage iokit_hid_usage_button_2(kHIDUsage_Button_2);
constexpr iokit_hid_usage iokit_hid_usage_button_3(kHIDUsage_Button_3);
constexpr iokit_hid_usage iokit_hid_usage_button_4(kHIDUsage_Button_4);
constexpr iokit_hid_usage iokit_hid_usage_button_5(kHIDUsage_Button_5);
constexpr iokit_hid_usage iokit_hid_usage_button_6(kHIDUsage_Button_6);
constexpr iokit_hid_usage iokit_hid_usage_button_7(kHIDUsage_Button_7);
constexpr iokit_hid_usage iokit_hid_usage_button_8(kHIDUsage_Button_8);
constexpr iokit_hid_usage iokit_hid_usage_button_9(kHIDUsage_Button_9);
constexpr iokit_hid_usage iokit_hid_usage_button_10(kHIDUsage_Button_10);
constexpr iokit_hid_usage iokit_hid_usage_button_11(kHIDUsage_Button_11);
constexpr iokit_hid_usage iokit_hid_usage_button_12(kHIDUsage_Button_12);
constexpr iokit_hid_usage iokit_hid_usage_button_13(kHIDUsage_Button_13);
constexpr iokit_hid_usage iokit_hid_usage_button_14(kHIDUsage_Button_14);
constexpr iokit_hid_usage iokit_hid_usage_button_15(kHIDUsage_Button_15);
constexpr iokit_hid_usage iokit_hid_usage_button_16(kHIDUsage_Button_16);
constexpr iokit_hid_usage iokit_hid_usage_button_17(kHIDUsage_Button_17);
constexpr iokit_hid_usage iokit_hid_usage_button_18(kHIDUsage_Button_18);
constexpr iokit_hid_usage iokit_hid_usage_button_19(kHIDUsage_Button_19);
constexpr iokit_hid_usage iokit_hid_usage_button_20(kHIDUsage_Button_20);
constexpr iokit_hid_usage iokit_hid_usage_button_21(kHIDUsage_Button_21);
constexpr iokit_hid_usage iokit_hid_usage_button_22(kHIDUsage_Button_22);
constexpr iokit_hid_usage iokit_hid_usage_button_23(kHIDUsage_Button_23);
constexpr iokit_hid_usage iokit_hid_usage_button_24(kHIDUsage_Button_24);
constexpr iokit_hid_usage iokit_hid_usage_button_25(kHIDUsage_Button_25);
constexpr iokit_hid_usage iokit_hid_usage_button_26(kHIDUsage_Button_26);
constexpr iokit_hid_usage iokit_hid_usage_button_27(kHIDUsage_Button_27);
constexpr iokit_hid_usage iokit_hid_usage_button_28(kHIDUsage_Button_28);
constexpr iokit_hid_usage iokit_hid_usage_button_29(kHIDUsage_Button_29);
constexpr iokit_hid_usage iokit_hid_usage_button_30(kHIDUsage_Button_30);
constexpr iokit_hid_usage iokit_hid_usage_button_31(kHIDUsage_Button_31);
constexpr iokit_hid_usage iokit_hid_usage_button_32(kHIDUsage_Button_32);

//
// iokit_hid_usage_page_consumer
//

constexpr iokit_hid_usage iokit_hid_usage_consumer_consumer_control(kHIDUsage_Csmr_ConsumerControl);
constexpr iokit_hid_usage iokit_hid_usage_consumer_power(kHIDUsage_Csmr_Power);
constexpr iokit_hid_usage iokit_hid_usage_consumer_display_brightness_increment(kHIDUsage_Csmr_DisplayBrightnessIncrement);
constexpr iokit_hid_usage iokit_hid_usage_consumer_display_brightness_decrement(kHIDUsage_Csmr_DisplayBrightnessDecrement);
constexpr iokit_hid_usage iokit_hid_usage_consumer_fast_forward(kHIDUsage_Csmr_FastForward);
constexpr iokit_hid_usage iokit_hid_usage_consumer_rewind(kHIDUsage_Csmr_Rewind);
constexpr iokit_hid_usage iokit_hid_usage_consumer_scan_next_track(kHIDUsage_Csmr_ScanNextTrack);
constexpr iokit_hid_usage iokit_hid_usage_consumer_scan_previous_track(kHIDUsage_Csmr_ScanPreviousTrack);
constexpr iokit_hid_usage iokit_hid_usage_consumer_eject(kHIDUsage_Csmr_Eject);
constexpr iokit_hid_usage iokit_hid_usage_consumer_play_or_pause(kHIDUsage_Csmr_PlayOrPause);
constexpr iokit_hid_usage iokit_hid_usage_consumer_mute(kHIDUsage_Csmr_Mute);
constexpr iokit_hid_usage iokit_hid_usage_consumer_volume_increment(kHIDUsage_Csmr_VolumeIncrement);
constexpr iokit_hid_usage iokit_hid_usage_consumer_volume_decrement(kHIDUsage_Csmr_VolumeDecrement);
constexpr iokit_hid_usage iokit_hid_usage_consumer_ac_pan(kHIDUsage_Csmr_ACPan);

//
// iokit_hid_usage_page_apple_vendor
//

constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_top_case(0x0001);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_display(0x0002);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_accelerometer(0x0003);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_ambient_light_sensor(0x0004);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_temperature_sensor(0x0005);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_keyboard(0x0006);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_headset(0x0007);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_proximity_sensor(0x0008);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_gyro(0x0009);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_compass(0x000A);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_device_management(0x000B);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_trackpad(0x000C);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_top_case_reserved(0x000D);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_motion(0x000E);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_keyboard_backlight(0x000F);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_device_motion_lite(0x0010);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_force(0x0011);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_bluetooth_radio(0x0012);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_orb(0x0013);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_accessory_battery(0x0014);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_humidity(0x0015);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_hid_event_relay(0x0016);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_nx_event(0x0017);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_nx_event_translated(0x0018);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_nx_event_diagnostic(0x0019);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_homer(0x0020);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_color(0x0021);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_accessibility(0x0022);

//
// iokit_hid_usage_page_apple_vendor_keyboard
//

constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_keyboard_spotlight(0x0001);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_keyboard_dashboard(0x0002);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_keyboard_function(0x0003);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_keyboard_launchpad(0x0004);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_keyboard_reserved(0x000a);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_keyboard_caps_lock_delay_enable(0x000b);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_keyboard_power_state(0x000c);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_keyboard_expose_all(0x0010);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_keyboard_expose_desktop(0x0011);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_keyboard_brightness_up(0x0020);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_keyboard_brightness_down(0x0021);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_keyboard_language(0x0030);

//
// iokit_hid_usage_page_apple_vendor_multitouch
//

constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_multitouch_power_off(0x0001);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_multitouch_device_ready(0x0002);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_multitouch_external_message(0x0003);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_multitouch_will_power_on(0x0004);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_multitouch_touch_cancel(0x0005);

//
// iokit_hid_usage_page_apple_vendor_top_case
//

constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_top_case_keyboard_fn(0x0003);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_top_case_brightness_up(0x0004);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_top_case_brightness_down(0x0005);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_top_case_video_mirror(0x0006);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_top_case_illumination_toggle(0x0007);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_top_case_illumination_up(0x0008);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_top_case_illumination_down(0x0009);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_top_case_clamshell_latched(0x000a);
constexpr iokit_hid_usage iokit_hid_usage_apple_vendor_top_case_reserved_mouse_data(0x00c0);
} // namespace osx
} // namespace pqrs

namespace std {
template <>
struct hash<pqrs::osx::iokit_hid_usage> : type_safe::hashable<pqrs::osx::iokit_hid_usage> {
};
} // namespace std
